version: "3"
services:
 blog:
  image: dkyocn/vagrant_blog
  container_name: blog
  ports:
   - "8080:8080"
  depends_on:
   - db
  links:
   - db
 db:
  image: mysql
  container_name: db
  environment:
   MYSQL_ROOT_PASSWORD: xiirocks22
   MYSQL_DATABASE: blog
   MYSQL_USER: cos
   MYSQL_PASSWORD: xiirocks22
  volumes:
   - ./data/mysql:/var/lib/mysql
  ports:
   - "3306:3306"
